name: Enforce PRs only from 'develop' branch

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Block PRs not from develop
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "::error::You can only merge into main from develop."
            exit 1
          fi
